name: Build and Deploy Fun7

on:
  # Trigger build on push to any branch
  push:

  # Trigger pull request builds for any branch
  pull_request:

  # Trigger on GitHub release creation
  release:
    types: [published]

jobs:
  build:
    # Always trigger build on push, pull request, or release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Authenticate to Google Cloud
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_KEY }}

    # Configure Docker to use the gcloud CLI as a credential helper
    - name: Set up Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

    # Build and tag Docker image
    - name: Build Docker image
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
          # Tag image with 'dev' for the dev branch
          docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fun7/${{ secrets.IMAGE_NAME }}:dev .
        elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          # Tag image with 'latest' for the main branch
          docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fun7/${{ secrets.IMAGE_NAME }}:latest .
        elif [[ "${{ github.event_name }}" == "release" ]]; then
          # Tag image with release version (e.g., v1.0.0)
          docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fun7/${{ secrets.IMAGE_NAME }}:${{ github.event.release.tag_name }} .
        else
          # For other branches, use the branch name as the tag
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fun7/${{ secrets.IMAGE_NAME }}:${BRANCH_NAME} .
        fi

    # Push Docker image to GAR
    - name: Push Docker image to GAR
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
          echo "TAG=dev" >> $GITHUB_ENV
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fun7/${{ secrets.IMAGE_NAME }}:dev
        elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "TAG=latest" >> $GITHUB_ENV
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fun7/${{ secrets.IMAGE_NAME }}:latest
        elif [[ "${{ github.event_name }}" == "release" ]]; then
          echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fun7/${{ secrets.IMAGE_NAME }}:${{ github.event.release.tag_name }}
        else
          # Push for other branches
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          echo "TAG=${BRANCH_NAME}" >> $GITHUB_ENV
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fun7/${{ secrets.IMAGE_NAME }}:${BRANCH_NAME}
        fi

  deploy:
    # Only trigger deployment if the push is to main or if it's a release event
    needs: build
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    # Deploy with Terraform
    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEY }}
        image_tag: ${{ env.TAG }}           # Use the tag set during the build
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        region: ${{ secrets.REGION }}
        image_name: ${{ secrets.IMAGE_NAME }}

