name: Build and Push to GAR

on:
  # Trigger on push to main or dev branches
  push:
    branches:
      - main
      - dev

  # Trigger when a pull request is merged to main or dev branches
  pull_request:
    branches:
      - main
      - dev
    types: [closed]

  # Trigger on GitHub release creation
  release:
    types: [published]

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Authenticate to Google Cloud
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_KEY }}

    # Configure Docker to use the gcloud CLI as a credential helper
    - name: Set up Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker {{ env.REGION }}-docker.pkg.dev

    # Build and tag Docker image
    - name: Build Docker image
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
          # Tag image with 'dev' for the dev branch
          docker build -t {{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fun7/${{ env.IMAGE_NAME }}:dev .
        elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          # Tag image with 'latest' for the main branch
          docker build -t {{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fun7/connectivity-test:latest .
        elif [[ "${{ github.event_name }}" == "release" ]]; then
          # Tag image with release version (e.g., v1.0.0)
          docker build -t {{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fun7/connectivity-test:${{ github.event.release.tag_name }} .
        fi

    # Push Docker image to GCR/GAR
    - name: Push Docker image to GAR
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
          echo "TAG=dev" >> $GITHUB_ENV
          docker push {{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fun7/${{ env.IMAGE_NAME }}:dev
        elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "TAG=latest" >> $GITHUB_ENV
          docker push {{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fun7/${{ env.IMAGE_NAME }}:latest
        elif [[ "${{ github.event_name }}" == "release" ]]; then
          echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          docker push {{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fun7/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
        fi
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve
      env:
        image_tag: ${{ env.TAG }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        region: ${{ env.REGION }}
        image_name: ${{ env.IMAGE_NAME }}

